### ISSUE TITLE
java.lang.NullPointerException in 1.12.2

### ISSUE THREAD

**Issue by InuYasha86000** [igentuman/EnderStorage-continuation#6]
I just updated enderstorage to 1.12.2-2.4.9, was testing it in a fresh new world and an error popped up:

Time: 2023-04-02 13:10:36 PDT
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(Util.java:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at codechicken.enderstorage.manager.EnderStorageManager.getStorage(EnderStorageManager.java:170)
    at codechicken.enderstorage.network.TankSynchroniser$PlayerItemTankCache.track(TankSynchroniser.java:205)
    at codechicken.enderstorage.network.TankSynchroniser$PlayerItemTankCache.handleVisiblityPacket(TankSynchroniser.java:254)
    at codechicken.enderstorage.network.TankSynchroniser.handleVisiblityPacket(TankSynchroniser.java:278)
    at codechicken.enderstorage.network.EnderStorageSPH.handlePacket(EnderStorageSPH.java:18)
    at codechicken.lib.packet.PacketCustom$ServerInboundHandler.handle(PacketCustom.java:135)
    at codechicken.lib.packet.PacketCustom$ServerInboundHandler.lambda$handle$0(PacketCustom.java:133)
    at codechicken.lib.packet.PacketCustom$ServerInboundHandler$$Lambda$4469/807654204.run(Unknown Source)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(Util.java:529)
    ... 5 more

it did NOT crash MY minecraft as I think I have a mod that prevents minor bugs from shutting down the game completely. it did not kick me out of the world either, just an error that popped up in the top right of the screen.

**Comment by MasterEnderman** [comment]
I have the same issue. Here is my "crash-report": https://gist.github.com/MasterEnderman/e2e185de057d295a811b2296b86ff4ed
